site_name: CommonOutcomes Wiki
nav:
  - Home: index.md
  - Co-modelling change: change.md
  - Modelling Axes:
    - Semantics of change: semantics.md
    - Graph of change: graph.md
    - Evolving change: evolving.md
    - Support for change: support.md
    - Translating change: translating.md
  - In Practice:
    - Exploring: exploring.md
    - Creating & editing: editing.md
    - Collaborating: collaborating.md
  - Links:
    - CommonOutcomes: https://commonoutcomes.org
    - CommonGraph: https://github.com/comodelling/commongraph/
    - Comodelling: https://comodelling.org

theme: readthedocs
markdown_extensions:
  - footnotes
  - admonition
  - pymdownx.superfences
plugins:
  - search
  - mermaid2
copyright: Copyright © Mario Morvan 2025 — licensed under CC BY-SA 4.0